Repository openshift/file-integrity-operator, pull requests merged in 2019-12, with the labels that each got.

#1 Add OWNERS file
  OWNERS
Labels: size/XS

#2 Change references to old repo to the openshift org
  cmd/manager/main.go
  go.mod
  pkg/apis/addtoscheme_fileintegrity_v1alpha1.go
  pkg/controller/add_configmap.go
  pkg/controller/add_fileintegrity.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: size/S

#3 Add Dockerfile for CI usage
  Dockerfile.ci
Labels: size/M

#5 Up timeout for cleanup and wait
  tests/e2e/helpers.go
Labels: size/XS

#4 Enhance Makefile to match compliance-operator
  Makefile
Labels: size/L

#6 update go mod
  go.mod
  go.sum
Labels: size/S

#8 Add GOPROXY and GOSUMDB to our go invocation
  Makefile
Labels: size/XS

#10 Revert "Add GOPROXY and GOSUMDB to operator-sdk call"
  Makefile
Labels: size/S

#7 Add FileIntegrityStatus controller
  deploy/crds/file-integrity.openshift.io_fileintegrities_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.openapi.go
  pkg/common/util.go
  pkg/controller/add_status.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/fileintegrity/config.go
  pkg/controller/status/status_controller.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/L

#11 Redirect output of `oc whoami`
  Makefile
Labels: approved, lgtm, size/XS

#16 schedule operator to run on masters
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#17 add an e2e test for a missing AIDE configmap
  pkg/controller/fileintegrity/config_defaults.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#20 Up timeout to 15 min
  tests/e2e/helpers.go
Labels: approved, lgtm, size/XS

#23 Unset GOFLAGS before operator-sdk call
  Makefile
Labels: approved, lgtm, size/XS

#22 e2e: poll for configMap changes instead of status
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/M

#25 Add status condition types
  deploy/crds/file-integrity.openshift.io_fileintegrities_crd.yaml
  doc/status.md
  go.mod
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.openapi.go
  pkg/common/constants.go
  pkg/common/util.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  pkg/controller/status/status_controller.go
Labels: approved, lgtm, size/L

#26 Add logcollector code
  Dockerfile.ci
  Makefile
  build/Dockerfile
  cmd/logcollector/main.go
  cmd/manager/main.go
  go.mod
  go.sum
  images/logcollector/Dockerfile
  images/logcollector/Dockerfile.ci
  pkg/common/constants.go
  vendor/github.com/cenkalti/backoff/v3/.gitignore
  vendor/github.com/cenkalti/backoff/v3/.travis.yml
  vendor/github.com/cenkalti/backoff/v3/LICENSE
  vendor/github.com/cenkalti/backoff/v3/README.md
  vendor/github.com/cenkalti/backoff/v3/backoff.go
  vendor/github.com/cenkalti/backoff/v3/context.go
  vendor/github.com/cenkalti/backoff/v3/exponential.go
  vendor/github.com/cenkalti/backoff/v3/go.mod
  vendor/github.com/cenkalti/backoff/v3/retry.go
  vendor/github.com/cenkalti/backoff/v3/ticker.go
  vendor/github.com/cenkalti/backoff/v3/tries.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL
