Repository openshift/file-integrity-operator, pull requests merged in 2020-09, with the labels that each got.

#102 Add icon to CSV
  deploy/olm-catalog/file-integrity-operator/0.1.5/file-integrity-operator.v0.1.5.clusterserviceversion.yaml
Labels: approved, lgtm

#103 Remove duplicate icon key in CSV
  deploy/olm-catalog/file-integrity-operator/0.1.5/file-integrity-operator.v0.1.5.clusterserviceversion.yaml
Labels: approved, lgtm

#104 Bug 1861303: Migrate holdoff logic to daemonset
  cmd/manager/daemon.go
  cmd/manager/logcollector.go
  deploy/role.yaml
  go.sum
  pkg/controller/fileintegrity/fileintegrity_controller.go
  pkg/controller/node/node_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#105 Bug 1866805: Add notes to README
  README.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#106 api: Add description to spec.config keys to enable oc explain
  deploy/crds/fileintegrity.openshift.io_fileintegrities_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
Labels: approved, lgtm

#107 FI: Label the DS, pods and FileIntegrityNodeStatus with owner label
  cmd/manager/logcollector.go
  pkg/common/constants.go
  pkg/common/util.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, lgtm

#109 daemon: Shortcut the integrityInstanceLoop if a watch can't be found
  cmd/manager/daemon.go
Labels: approved

#110 Remove replaces: from CSV
  Dockerfile.ci
  cmd/manager/logcollector.go
  deploy/olm-catalog/file-integrity-operator/0.1.5/file-integrity-operator.v0.1.5.clusterserviceversion.yaml
Labels: approved, lgtm

#108 Bug 1826301: Mark the nodeStatus and the FI object as Error in case the config can't even be loaded
  cmd/manager/daemon.go
  deploy/crds/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.deepcopy.go
  pkg/common/util.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/status/status_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-medium, lgtm

#112 Bug 1869293: Add timestamp to daemon logs
  Makefile
  cmd/manager/logcollector.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-low, lgtm

#114 e2e: Be more resilient when setting node taints
  tests/e2e/helpers.go
Labels: approved, lgtm

#115 Reduce code-duplication in Makefile
  Makefile
Labels: approved, lgtm

#118 make: Download the opm binary
  Makefile
Labels: approved, lgtm

#119 Make: publish is no longer a target
  Makefile
Labels: approved, lgtm

#117 Several small cleanup patches
  pkg/controller/fileintegrity/fileintegrity_controller.go
  pkg/controller/node/node_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#116 Reload FI when the configMap the FI points to changes
  pkg/controller/fileintegrity/cm_to_fi_mapper.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved
