Repository openshift/file-integrity-operator, pull requests merged in 2020-03, with the labels that each got.

#45 Exclude /etc/kubernetes/manifests from default AIDE policy
  pkg/controller/fileintegrity/config_defaults.go
Labels: approved, lgtm, size/XS

#46 e2e: Change modify file path
  pkg/controller/fileintegrity/config_defaults.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/XS

#48 Move scc role
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M

#49 Add make release targets
  Makefile
Labels: approved, lgtm, size/M

#50 Explicitly set image tag when building operator image
  Makefile
Labels: approved, lgtm

#53 Remove unused functions
  tests/e2e/helpers.go
Labels: approved, lgtm

#54 make: Drop deprecated operator-sdk generate openapi, use generate crds instead
  Makefile
Labels: approved, lgtm

#55 Add annotation to force database re-init
  pkg/common/constants.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#52 Add numerical summary how many files were added, changed or removed
  cmd/logcollector/main.go
  deploy/crds/file-integrity.openshift.io_fileintegrities_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.openapi.go
  pkg/common/constants.go
  pkg/controller/configmap/configmap_controller.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#57 Operator-sdk v0.16.0 and additions
  Makefile
  go.mod
  go.sum
  tests/e2e/helpers.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/cmd.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/controller_kind.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/doc.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/entrypoint.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/register.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/role.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/scaffold.go
  vendor/github.com/operator-framework/operator-sdk/internal/util/k8sutil/k8sutil.go
  vendor/github.com/operator-framework/operator-sdk/internal/util/projutil/project_util.go
  vendor/github.com/operator-framework/operator-sdk/pkg/k8sutil/k8sutil.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/uclient.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/flags.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/logger.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/service-monitor.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/client.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/context.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/e2eutil/wait_util.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/framework.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/resource_creator.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/github.com/securego/gosec/.travis.yml
  vendor/github.com/securego/gosec/Makefile
  vendor/github.com/securego/gosec/go.sum
  vendor/github.com/securego/gosec/helpers.go
  vendor/github.com/securego/gosec/rules/subproc.go
  vendor/modules.txt
Labels: approved, lgtm
