Repository openshift/file-integrity-operator, pull requests merged in 2020-02, with the labels that each got.

#27 WIP: Take logcollector into use
  cmd/manager/main.go
  deploy/crds/file-integrity.openshift.io_fileintegrities_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.openapi.go
  pkg/common/constants.go
  pkg/common/util.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/fileintegrity/config_defaults.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, do-not-merge/work-in-progress, size/L

#35 update README.md
  README.md
Labels: approved, lgtm, size/L

#36 Tie AIDE config to FileIntegrity Object
  pkg/common/constants.go
  pkg/common/util.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  pkg/controller/status/status_controller.go
  tests/e2e/e2e_test.go
Labels: approved, size/M

#37 Expose nodeSelector option
  deploy/crds/file-integrity.openshift.io_fileintegrities_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/fileintegrity/v1alpha1/zz_generated.openapi.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, size/M

#33 Generate CSV for OLM
  Makefile
  README.md
  deploy/olm-catalog/file-integrity-operator/0.1.0/file-integrity-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/file-integrity-operator/0.1.0/file-integrity.openshift.io_fileintegrities_crd.yaml
  deploy/olm-catalog/file-integrity-operator/file-integrity-operator.package.yaml
  deploy/olm-catalog/operator-source.yaml
Labels: approved, lgtm, size/L

#38 Allow setting workload images through environment variables
  deploy/operator.yaml
  pkg/controller/fileintegrity/fileintegrity_controller.go
  pkg/controller/fileintegrity/utils.go
Labels: approved, lgtm, size/M

#39 Take file-integrity-operator org into use and enabling pushing all images
  Makefile
  deploy/operator.yaml
  pkg/controller/fileintegrity/utils.go
Labels: approved, lgtm, size/M

#34 e2e logcollector tests
  pkg/controller/fileintegrity/config_defaults.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#40 Test newly built workload images in e2e tests
  Makefile
Labels: approved, lgtm, size/M

#21 Delete DS pods instead of triggering a rolling update
  pkg/controller/configmap/configmap_controller.go
Labels: approved, lgtm, size/M

#41 Move e2e helpers functions to helpers.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/XL

#43 Rebase master on 4.4 branch
  Makefile
  deploy/operator.yaml
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/fileintegrity/config_defaults.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  pkg/controller/fileintegrity/utils.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, size/XL

#44 Refactor user configMap reconcile steps
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, lgtm, size/L
