Repository openshift/file-integrity-operator, pull requests merged in 2021-02, with the labels that each got.

#137 Bug 1923096: Update nodeSelector and Tolerations
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#138 Release v0.1.10
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegrities_crd.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
Labels: approved, lgtm

#141 Backport v0.1.10
  Makefile
  deploy/crds/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
Labels: approved

#142 backport v0.1.10
  Makefile
  deploy/crds/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
  tests/e2e/e2e_test.go
Labels: approved

#139 README.md: Add note about log compression
  README.md
Labels: approved

#143 Add Disconnected support annotation to CSV
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#144 Release v0.1.11
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved

#146 Backport v0.1.11
  README.md
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved

#148 Backport v0.1.11
  README.md
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved

#150 Enable OCP-provided monitoring services
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#151 Update container registry to registry.ci.openshift.org
  Dockerfile.ci
  Dockerfile.ocp
  images/aide/Dockerfile.ci
  images/logcollector/Dockerfile.ci
Labels: approved, lgtm

#149 daemon: Changes for running with pprof
  build/Dockerfile
  cmd/manager/daemon.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, lgtm

#152 Adds note about configMap annotation indicating compression of AIDE logs
  README.md
Labels: approved, lgtm

#153 Bug 1925105: daemon: Use RetryWatcher
  cmd/manager/daemon.go
  go.mod
  pkg/controller/fileintegrity/fileintegrity_controller.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
