Repository openshift/file-integrity-operator, pull requests merged in 2021-09, with the labels that each got.

#196 minor: adapt prometheusrule to only alert on currently existing nodes
  README.md
  cmd/manager/operator.go
Labels: ok-to-test

#195 Bug 1999186: Add MCO and CVO related config excludes
  pkg/controller/fileintegrity/config_defaults.go
  tests/e2e/helpers.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#197 Bug 1999054: Use ClusterRole/ClusterRoleBinding for monitoring perms
  deploy/olm-catalog/file-integrity-operator/manifests/monitoring_clusterrole.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/monitoring_clusterrolebinding.yaml
  deploy/role.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium

#198 Makefile: Rename IMAGE_FORMAT var
  Makefile
Labels: approved, lgtm

#199 Makefile: Apply monitoring resources during deploy-local
  Makefile
Labels: approved, lgtm

#200 Bug 2002519: Delete legacy daemonSets after upgrade
  Makefile
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#202 Release v0.1.19
  CHANGELOG.md
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, lgtm
