Repository openshift/file-integrity-operator, pull requests merged in 2021-01, with the labels that each got.

#125 Fix dev deployments in local clusters
  Makefile
  build/Dockerfile
  images/aide/Dockerfile
Labels: approved, lgtm

#126 Handle daemon updates
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, lgtm

#128 Update spf13/cobra deps and replace old gorilla/websocket
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/modules.txt
Labels: approved

#129 Release v0.1.8
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved

#132 Remove `-race` flag from manager build
  Makefile
Labels: approved

#133 Release v0.1.9
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#134 Bug 1921692: Add status columns to fileintegritynodestatus output
  deploy/crds/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegrities_crd.yaml
  deploy/olm-catalog/file-integrity-operator/manifests/fileintegrity.openshift.io_fileintegritynodestatuses_crd.yaml
  pkg/apis/fileintegrity/v1alpha1/fileintegrity_types.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
