Repository openshift/file-integrity-operator, pull requests merged in 2021-03, with the labels that each got.

#156 Bug 1927291: daemon: Use RetryWatcher and set GODEBUG=madvisedontneed=1
  cmd/manager/daemon.go
  go.mod
  pkg/controller/fileintegrity/fileintegrity_controller.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/modules.txt
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high

#155 Bug 1925134: daemon: Use RetryWatcher and set GODEBUG=madvisedontneed=1
  cmd/manager/daemon.go
  go.mod
  pkg/controller/fileintegrity/fileintegrity_controller.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/modules.txt
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high, lgtm

#154 Bug 1927291: daemon: Use RetryWatcher and set GODEBUG=madvisedontneed=1
  cmd/manager/daemon.go
  go.mod
  pkg/controller/fileintegrity/fileintegrity_controller.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/modules.txt
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-high

#157 logcollector: Only read log once in a buffered way
  cmd/manager/daemon.go
  cmd/manager/logcollector.go
Labels: approved, lgtm

#158 Release v0.1.12
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, do-not-merge/hold, lgtm

#159 Bug 1925105: Fix madvise setting
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#160 Release v0.1.13
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#164 Backport v0.1.13 - release-4.6
  Dockerfile.ci
  Dockerfile.ocp
  README.md
  build/Dockerfile
  cmd/manager/daemon.go
  cmd/manager/logcollector.go
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
  images/aide/Dockerfile.ci
  images/logcollector/Dockerfile.ci
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved

#163 Backport v0.1.13 - release-4.7
  Dockerfile.ci
  Dockerfile.ocp
  README.md
  build/Dockerfile
  cmd/manager/daemon.go
  cmd/manager/logcollector.go
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
  images/aide/Dockerfile.ci
  images/logcollector/Dockerfile.ci
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved

#162 Backport v0.1.13 - rhaos-4.6-rhel-8
  Dockerfile.ci
  Dockerfile.ocp
  README.md
  build/Dockerfile
  cmd/manager/daemon.go
  cmd/manager/logcollector.go
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
  images/aide/Dockerfile.ci
  images/logcollector/Dockerfile.ci
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved
