Repository openshift/file-integrity-operator, pull requests merged in 2022-07, with the labels that each got.

#253 Fix bad remote URL
  Makefile
Labels: approved, lgtm

#254 Release v0.1.26
  CHANGELOG.md
  bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
  config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm

#240 bug 2101393: operator: Set namespace label for alert
  cmd/manager/operator.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-medium, qe-approved

#258 Makefile: Add CATALOG_DEPLOY_NS variable for make catalog-deploy
  Makefile
Labels: approved, lgtm

#259 Bug 2104897: Use ClusterRole and local RoleBinding for daemon permissions
  Makefile
  bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/rbac/daemon_role.yaml
  config/rbac/daemon_rolebinding.yaml
  config/rbac/kustomization.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#247 Clarify the image repository used by default in the release process
  README.md
Labels: approved, lgtm

#261 Makefile: Fix build dir recipe override
  Makefile
Labels: approved, lgtm

#255 e2e: Use pod instead of ds for logcompress file toucher
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved

#265 Create LICENSE
  LICENSE
Labels: approved, lgtm

#266 Release v0.1.28
  CHANGELOG.md
  bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
  config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm

#267 Bug 2108475: Change daemon RBAC back to Role
  bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/rbac-daemon/daemon_rolebinding.yaml
  config/rbac/daemon_role.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#268 Makefile: push latest catalog for release
  Makefile
Labels: approved, lgtm

#270 Release v0.1.29
  CHANGELOG.md
  bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
  config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm

#272 Bug 2109153: Restore CSV ownership of ServiceAccounts
  Makefile
  bundle/manifests/file-integrity-daemon_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/file-integrity-daemon_v1_serviceaccount.yaml
  bundle/manifests/file-integrity-operator-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
  bundle/manifests/prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/default-bundle/kustomization.yaml
  config/default/kustomization.yaml
  config/rbac-daemon/kustomization.yaml
  config/rbac/daemon_rolebinding.yaml
  config/rbac/daemon_serviceaccount.yaml
  config/rbac/kustomization.yaml
  config/rbac/metrics_clusterrole.yaml
  config/rbac/metrics_rolebinding.yaml
  config/rbac/monitoring_clusterrolebinding.yaml
  config/rbac/operator_serviceaccount.yaml
  config/rbac/prometheus_rolebinding.yaml
  config/rbac/role.yaml
  config/rbac/service_account.yaml
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high, qe-approved

#274 Release v0.1.30
  CHANGELOG.md
  bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
  config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml
  version.Makefile
  version/version.go
Labels: approved, lgtm

#275 trivial: fix grammatical issue in README.md
  README.md
Labels: approved, lgtm

#276 e2e: Allow running against an existing deployment
  README.md
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
  tests/framework/framework.go
Labels: approved, lgtm
