Repository openshift/file-integrity-operator, pull requests merged in 2022-01, with the labels that each got.

#212 Bug 2033311: Move aide.reinit to /run
  cmd/manager/daemon.go
  cmd/manager/daemon_util.go
  pkg/controller/fileintegrity/config_defaults.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: bugzilla/valid-bug, approved, lgtm, bugzilla/severity-high

#213 Release v0.1.22
  CHANGELOG.md
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved

#214 CSV: We support FIPS
  deploy/olm-catalog/file-integrity-operator/manifests/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, lgtm
