Repository openshift/file-integrity-operator, pull requests merged in 2023-08, with the labels that each got.

#387 OCPBUGS-15090 remove leftover nodestatus
  pkg/controller/status/status_controller.go
Labels: approved, lgtm, qe-approved, docs-approved, px-approved

#413 OCPBUGS-17129: Ignore MCO node annotation files
  pkg/controller/fileintegrity/config_defaults.go
Labels: approved, lgtm, qe-approved, jira/severity-critical, jira/valid-reference

#420 dependabot: Use dependabot groups to group k8s updates together
  .github/dependabot.yml
Labels: approved, lgtm

#417 Add Marina to reviewers for PX approval
  OWNERS
Labels: approved, lgtm, qe-approved, docs-approved, px-approved

#424 OCPBUGS-14947: Fix hostmount propagation
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
