Repository openshift/file-integrity-operator, pull requests merged in 2023-03, with the labels that each got.

#304 Update prometheus/client_golang to 1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: approved, lgtm

#305 Update coreos/ignition/v2 to 2.14.0
  go.mod
  go.sum
  vendor/github.com/coreos/ignition/v2/config/shared/errors/errors.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/directory.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/file.go
  vendor/github.com/coreos/ignition/v2/config/v3_2/types/mode.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/ip.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/string_array.go
  vendor/modules.txt
Labels: approved, lgtm

#308 Configure dependabot
  .github/dependabot.yml
Labels: approved, lgtm

#311 Update golang version in Dockerfile for builds
  build/Dockerfile
Labels: approved, lgtm, qe-approved, docs-approved, px-approved

#310 Bump operator-sdk from 1.15.0 to 1.27.0
  Makefile
Labels: bugzilla/valid-bug, approved, lgtm, qe-approved, docs-approved, px-approved

#313 dependabot.yaml: Remove duplicate value
  .github/dependabot.yml
Labels: approved, lgtm, qe-approved, docs-approved, px-approved

#314 Use remote detection in release process
  Makefile
  utils/git-remote.sh
Labels: approved, lgtm, qe-approved, docs-approved, px-approved

#318 Update maintainers
  bundle/manifests/file-integrity-operator.clusterserviceversion.yaml
  config/manifests/bases/file-integrity-operator.clusterserviceversion.yaml
Labels: approved, qe-approved

#321 Update CI to use RHEL 9 and OpenShift 4.13
  Dockerfile.ci
Labels: bugzilla/valid-bug, approved
