Repository openshift/file-integrity-operator, pull requests merged in 2025-05, with the labels that each got.

#649 CMP-3381: Update the bundle pipeline to only run for specific changes
  .tekton/file-integrity-operator-bundle-push.yaml
Labels: approved, lgtm, jira/valid-reference

#650 CMP-3381: Configure Konflux to bump image SHAs
  .tekton/file-integrity-operator-push.yaml
Labels: approved, lgtm, jira/valid-reference

#651 CMP-3381: Update operator image reference
  bundle-hack/update_csv.go
Labels: approved, jira/valid-reference

#660 OCPBUGS-56409: Fix FIPS for aide container
  Dockerfile.ci
  Makefile
  build/Dockerfile
  build/Dockerfile.openshift
  build/guard/libaide_md5_guard.c
  cmd/manager/daemon_util.go
  konflux/rpms.lock.yaml
  pkg/common/util.go
Labels: approved, lgtm, qe-approved, docs-approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#674 Update digest for operator image
  bundle-hack/update_csv.go
Labels: approved

#675 Update pipeline runs to include branch name as image tag
  .tekton/file-integrity-operator-bundle-master-push.yaml
  .tekton/file-integrity-operator-bundle-push.yaml
  .tekton/file-integrity-operator-master-push.yaml
  .tekton/file-integrity-operator-push.yaml
Labels: approved, ok-to-test, lgtm, qe-approved, docs-approved, px-approved

#676 Update pipeline runs to include branch name as image tag
  .tekton/file-integrity-operator-1-3-push.yaml
  .tekton/file-integrity-operator-bundle-1-3-push.yaml
  .tekton/file-integrity-operator-bundle-master-push.yaml
  .tekton/file-integrity-operator-bundle-push.yaml
  .tekton/file-integrity-operator-master-push.yaml
  .tekton/file-integrity-operator-push.yaml
Labels: approved

#678 Block MD5 without failing AIDE
  build/guard/libaide_md5_guard.c
  cmd/manager/daemon_util.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, lgtm, qe-approved, docs-approved, px-approved

#679 backport Block MD5 without failing AIDE
  build/guard/libaide_md5_guard.c
  cmd/manager/daemon_util.go
  pkg/controller/fileintegrity/fileintegrity_controller.go
Labels: approved, lgtm
