Repository openshift/file-integrity-operator, pull requests merged in 2025-06, with the labels that each got.

#689 Fix output image value for Y-stream repos
  .tekton/file-integrity-operator-bundle-release-1-3-pull-request.yaml
  .tekton/file-integrity-operator-bundle-release-1-3-push.yaml
  .tekton/file-integrity-operator-release-1-3-pull-request.yaml
  .tekton/file-integrity-operator-release-1-3-push.yaml
Labels: approved

#686 Update konflux config and update script for dev application
  .tekton/file-integrity-operator-bundle-dev-pull-request.yaml
  .tekton/file-integrity-operator-bundle-dev-push.yaml
  .tekton/file-integrity-operator-dev-pull-request.yaml
  .tekton/file-integrity-operator-dev-push.yaml
  bundle-hack/update_csv.go
Labels: approved

#703 CMP-3424: Remove dependabot configuration
  .github/dependabot.yml
Labels: approved, jira/valid-reference

#720 CMP-3441: Add a github action for gosec
  .github/workflows/gosec.yaml
Labels: approved, jira/valid-reference

#733 Add licenses dir with operator LICENSE
  build/Dockerfile.openshift
Labels: approved

#739 Make bundle pipelines runs more restricted
  .tekton/file-integrity-operator-bundle-release-1-3-pull-request.yaml
  .tekton/file-integrity-operator-bundle-release-1-3-push.yaml
  .tekton/file-integrity-operator-release-1-3-pull-request.yaml
  .tekton/file-integrity-operator-release-1-3-push.yaml
Labels: approved, lgtm

#740 Nudge the bundle build after #739
  bundle-hack/update_csv.go
Labels: approved
